server:
  port: 8020
spring:
  application:
    name: producer
  rabbitmq:
    host: 
    port: 5672 # 5672一般用于信息传递，15672用于web管理
    username: mall
    password: mall
    #    virtual-host: / 默认的host,应该保证用户具有该路径的权限，否则需要自定义用户具有权限的路径
